server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: smapbcn
    password: devpass

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
