spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  security:
    jwt:
      secret: SMAP_SECRET_LOCAL
  smap:
    jwt:
      secret: SMAP_SECRET_LOCAL

logging:
  level:
    root: INFO
    com.smap: DEBUG

springdoc:
  swagger-ui:
    enabled: true